### ISSUE TITLE
import/no-cycle should not trigger for Flow imports

### ISSUE THREAD

**Issue by murrayju** [benmosher/eslint-plugin-import#1343]
This is a regression of #1098 (fix in PR #1126) that was re-introduced in v2.17.0.

v2.16.0 works as expected. v2.17.2 still has this regression.

**Comment by jonathanrdelgado** [comment]
Not sure if it is on the radar of this project, but it is also worth mentioning there is a similar issue with Typescript.

**Comment by ljharb** [comment]
@jonathanrdelgado it is, if an issue is filed - please file one if there isn’t one already.

**Comment by SebastienGllmt** [comment]
Has anybody had time to look into this? 2.17.3 still has this regression 🙏

**Comment by SebastienGllmt** [comment]
Hey folks. I looked into this and it turns out the reason for the regression is that [the original fix](https://github.com/benmosher/eslint-plugin-import/pull/1126/files#diff-a2f3be196673e4fb72d7f55c98f3499bR33) was subsequently removed by [this pr](https://github.com/benmosher/eslint-plugin-import/pull/1218/files#diff-a2f3be196673e4fb72d7f55c98f3499bL34)

if you look at the current state of the file, it hasn't changed since this break
https://github.com/benmosher/eslint-plugin-import/blob/master/src/rules/no-cycle.js#L34

**Comment by ljharb** [comment]
Thanks, seems like a simple PR to restore it, but with a test case to prevent it from being removed again.

**Comment by SebastienGllmt** [comment]
I don't really have context for why this was removed so I may not be the best person for this. I tried to write a test case to reproduce the error we get on our codebase but to my surprise, no error occurs. It could be that I'm not using the tests properly but it could also be that this error only is reproducible with a certain kind of setup.

**Comment by dominicfraser** [comment]
`https://github.com/benmosher/eslint-plugin-import/pull/1494` was opened to fix this on 5th Oct, but as yet has not been approved.
cc: @ljharb

**Comment by ljharb** [comment]
Yes, thanks, I'm aware. It's been on my list.

**Comment by dominicfraser** [comment]
Great, thanks 😀

**Comment by dominicfraser** [comment]
Thank you for this :D :D
