### ISSUE TITLE
Treat paths with `node_modules` as or next in order to "external" modules

### ISSUE THREAD

**Issue by brettz9** [benmosher/eslint-plugin-import#1346]
Hi,

I enjoy your plugin and use it in my own config ([eslint-config-ash-nazg](https://github.com/brettz9/eslint-config-ash-nazg)).

I am wondering whether you might add a condition to the `order` rule which gave special treatment when a path contained a directory `node_modules`, treating it with the same or just lower priority as "external" modules stated without a qualified path?

With ESM distributions, one can build applications, albeit for modern browsers only, which directly consume module builds without the need for doing one's own compilation. In these browser applications which avoid the need for bundling, one must write out the `node_modules` paths, but it would be nice to treat them as being external as far as import ordering.

Thanks again for the helpful plugin!

**Comment by ljharb** [comment]
I don’t personally see any value in supporting use cases that lack a build process, since that’s something i feel is required for modern web dev for the foreseeable future - especially once node unflags its ESM implementation. Additionally, for targeting browsers without a build process you’ll want to keep using bare imports in your code, and use an import map to statically rewrite them to the node_modules path, which would make this request unnecessary.

I think a generic mechanism for defining your own groups, however, would support this use case without enshrining a bad (and already legacy) practice in this plugin. For that, see #674.

**Comment by brettz9** [comment]
Wasn't aware of the import map proposal, thanks!

**Comment by brettz9** [comment]
But as far as use cases, it is convenient to use on demos on which one doesn't need to wait for build steps to debug some changes. The feedback loop is faster. But again, the import map proposal sounds like it would meet my needs whenever it may become implemented.

**Comment by ljharb** [comment]
It's shipped in Chrome already (possibly behind a flag)
