### ISSUE TITLE
Support the .mjs file extension out of the box

### ISSUE THREAD

**Issue by jaydenseric** [benmosher/eslint-plugin-import#1359]
The `.mjs` extension is not supported out of the box, so if you want the `import/named` rule to do anything when importing from `.mjs` files you have to manually add support via ESLint config `settings`:

```json
{
  "settings": {
    "import/extensions": [".mjs", ".js"],
    "import/resolver": {
      "node": {
        "extensions": [".mjs", ".js"]
      }
    }
  }
}
```

This list should probably be a little longer, since node resolves several file extensions in order of preference. Also, for people needing to support `.jsx`, be sure to add that too.

TBH I don't fully understand why the `import/extensions`  and `['import/resolver'].node.extensions` settings are seperate, so I'm not sure if both need to be updated?

It took me a few hours to work this out, because the `import/no-unresolved` rule works with `.mjs`; only `import/named` does not.

**Comment by ljharb** [comment]
node doesn’t really resolve mjs at all yet - experimental things don’t count. I go back and forth on whether mjs should be supported at all yet.

There’s a difference between the list of extensions to resolve (which should match node), and the list of extensions to apply the rule to.

I’m not sure what’s actionable about this issue - is it just trying to inform other users?

**Comment by jaydenseric** [comment]
> I go back and forth on whether mjs should be supported at all

I think you mean automatic file extension/directory index resolution in ESM/`.mjs`? The file extension `.mjs` is certainly here to stay.

I've read many of [your comments at nodejs/modules](https://github.com/nodejs/modules/pull/327/files#diff-ca74c0cde3cb22f80be5e24c448f457cR15), so I am aware of the back and forth.

> I’m not sure what’s actionable about this issue - is it just trying to inform other users?

What's actionable is in the title: "Support the .mjs file extension out of the box". Node.js v8, 9 and 10 all resolve `.mjs` in `--experimental-modules` mode, and yes, thousands of people rely on that mode. Webpack resolves `.mjs` before `.js`, and a lot of people use Webpack. Node.js v12 still can resolve `.mjs` before `.js`, just with an extra flag. There is still the possibility that this behavior will ship in the final Node.js ESM implementation.

Actions:

- The inconsistency doesn't make sense, either:
   1. The `import/no-unresolved` rule should stop resolving `.mjs` files.
   2. The `import/named` rule should be made to resolve `.mjs` files.
- If option (1) is actioned, document clearly how users can opt-in to resolving `.mjs` to support the many `--experimental-modules` and Webpack users in this boat.

**Comment by jaydenseric** [comment]
Keep in mind, to be true to the Node.js v12 `--experimental-modules` implementation, extensionless imports should not work even when resolving `.js` files, and ESM should not be in `.js` files.

**Comment by ljharb** [comment]
Yes, the changes in the modules implementation are the very reason I’d lean towards “no support at all until unflagging”.

Relying on an experimental flag is unwise at best; that’s not a convincing argument.

I definitely agree that the inconsistency is a problem - however, no-unresolved can’t be changed without it being a breaking change, and due to the current status in the node implementation, i don’t think it’s wise to add mjs to named (or any other rule) at this time.

iow, i think the best practice if you are using the flagged implementation in node is to explicitly include `.mjs` everywhere appropriate in your eslint config - and i think the downsides of the current inconsistency are far less than the downsides of adding more defaults that are still subject to change.

The extension is decidedly here to stay - but automatically resolving it is still an open question.

**Comment by ljharb** [comment]
… an open question that was answered in #955.

Also, node v13.3+ has unflagged ESM.
