### ISSUE TITLE
import/named gets lost when package exports ES6 modules

### ISSUE THREAD

**Issue by eliseumds** [benmosher/eslint-plugin-import#1460]
I have a package exporting ES6 code only with these files in the *dist* directory:

```js
// index.js
export { default as A } from './A';
```

```ts
// index.d.ts
export * from './types';
export { default as A } from './A';
```

And then, when I use it like:

```ts
import { A, SomeType } from 'my-package'; 
```

ESLint complains with:

```
error  SomeType not found in 'my-package'  import/named
```

No TS errors. If I export just types from *my-package*, it works fine. It gets lost when it's mixed with concrete exports. Compiling to CommonJS makes it work but I lose tree-shaking.

My *.eslintrc.js* file:

```js
const path = require('path');

module.exports = {
  extends: [
    'airbnb-base',
    'plugin:@typescript-eslint/recommended',
    'prettier/@typescript-eslint',
    'plugin:prettier/recommended',
    'plugin:import/typescript',
  ],
  settings: {
    'import/resolver': {
      node: {
        extensions: ['.js', '.ts'],
        // Also lookup in the root directory (it's a Lerna repo)
        moduleDirectory: [path.resolve('./node_modules'), path.resolve('../../../node_modules')],
      },
    },
    'import/ignore': ['shared/'],
  },
};
```

**Comment by ljharb** [comment]
I don't understand, you have "not ES5 CJS" in a published package's `main`? tree-shaking works fine in CJS, it's just that webpack doesn't enable it; tree-shaking is also only needed when you use manifest exports instead of consumers deep-importing exactly what they need.

As for the `d.ts` file, see #1341.

**Comment by eliseumds** [comment]
Yes, the package serves ES6 files (I have both "main" and "typings" fields defined). This is a private internal Lerna package.

Not using manifest exports because of a linting issue doesn't sound like a solution to me. Would you suggest that I output CommonJS and use something like https://github.com/indutny/webpack-common-shake?

I doesn't look like there's any issue with the `.d.ts` file. The types are all there for tsc to read, and also for ESLint, but only when I don't export other things in the same file (ES6) file.

**Comment by ljharb** [comment]
I'd definitely suggest that for public packages, including that "main" should always be CJS ES5 - but it's fair that for internal packages you can go as nuts as you like :-)

The reason to avoid manifest exports is because it's sloppy, and is the whole reason that treeshaking is needed in the first place.

The issue, I think, is that this eslint plugin isn't merging d.ts exports with .js exports, which is #1341 - and it should do that, if it's possible.

**Comment by eliseumds** [comment]
Ye, I'll live with it for now. I saw the other issue but wasn't sure whether they were related. Thanks for the prompt responses and the project contributions.

**Comment by floviolleau** [comment]
Hi,

I have exactly the same issue.

**Comment by paztis** [comment]
Hi

Error is still present for me as well.
My modules are not delivering at all a es5 version
I've multiple modules in a monorepo, and if module A is re-exporting the named exports of module B, the problem is always present.

module A
```
export const foo = "I'm so foo"
```

module B
```
export * from 'moduleA';
```

module C
```
import {foo} from 'moduleB'; // error  foo not found in 'moduleB'  import/named
```


This only works if I explicitly say what I export from module A

module B
```
export {foo} from 'moduleA';
```

But with this each time I will update the moduleA, I will always need to update also the moduleB...
That's the full reason of the export * feature.

**Comment by paztis** [comment]
The problem might came from ExportMap.js `hasDeep` mechanism. It doesn't detect we're re-exporting things ?

**Comment by JounQin** [comment]
@ljharb I think this issue can be closed also?

**Comment by ljharb** [comment]
Please file a new issue if this is still a problem.
