### ISSUE TITLE
Can't resolve 'react-select-virtualized'

### ISSUE THREAD

**Issue by scottc-netflix** [benmosher/eslint-plugin-import#1531]
Getting a false error here because 'react-select-virtualized' is there and working fine, eslint-plugin-import thinks it can't be found though and it's the only package out of about 70 that has this problem. The errors could be more helpful to show where it looked and didn't find the package at. Tried a bunch of ways to resolve or debug this issue and no luck with anything.

I don't really get why we need this plugin and a bunch of other resolver plugins on top of that when everything "just worked" out of the box with Babel 6.

These are the relevant versions I'm on if that helps:
eslint-plugin-import: 2.8.0
eslint: 6.6.0
babel-eslint: 10.0.3
@babel/core: 7.6.4
react-select-virtualized: 2.3.1

**Comment by ljharb** [comment]
That's because the package has a bug. See https://unpkg.com/browse/react-select-virtualized@2.3.1/ - it lists a main of `dist/index.min.js`, a module of `dist/index.min.es.js`, and a jsnext:main of `dist/index.es.js`.

 - https://unpkg.com/browse/react-select-virtualized@2.3.1/dist/index.min.js works
 - https://unpkg.com/browse/react-select-virtualized@2.3.1/dist/index.min.es.js works
 - https://unpkg.com/browse/react-select-virtualized@2.3.1/dist/index.js fails

Please file an issue on [the project repo](https://github.com/guiyep/react-select-virtualized#readme) instead.

**Comment by scottc-netflix** [comment]
@ljharb Thanks!

**Comment by ljharb** [comment]
https://github.com/guiyep/react-select-virtualized/issues/49
