### ISSUE TITLE
import/no-extraneous-dependencies can't disable error message for specific files

### ISSUE THREAD

**Issue by GarfieldDeepClone** [benmosher/eslint-plugin-import#1700]
Hi :)

In my eslintrc file I'm overriding the no-extra... rule like this:
```
"import/no-extraneous-dependencies": ["error", {
			"devDependencies": [
				"**/*.ts"
			]
		}]
```
So I don't want to see an error message for all .ts files. But it doesn't work.

The import that is marked as error:
`import { $, browser} from 'protractor';`

Protractor is not directly in the package.json, but it's added via another dev-dependency:
`grunt-protractor-runner`

So I'm not sure if I can use 'devDependencies' to exclude files, but I tried all of them with no luck(devDependencies, optionalDependencies, peerDependencies and bundledDependencies)

**Comment by ljharb** [comment]
I'm confused, why would you want all your TS files to allow dev deps?

In general tho, if you're importing from `protractor`, it *must* be in your package.json - otherwise you're relying on the accident of npm hoisting it to the top level.

**Comment by aqumus** [comment]
In a monorepo, Is there a way to mask certain dependencies and still let particular file lint about no-extraneous-dependencies when dependencies other than masked one's are imported
For eg:

##### MonoRepo Root level package.json
`
{
   devDependencies: {
        "react-testing-library": "^x.y.z"
   }
}
`
workspace module A package.json doesn't include `"react-testing-library"` as devDependencies (since its already been present at root level)
Now what we need is to mask "react-testing-library" no-extraneous-dependencies linting from every `spec.js` files, Is that possible?

**Comment by ljharb** [comment]
@aqumus in that case, it should be an explicit dev dep of each subproject as well as the root.

**Comment by aqumus** [comment]
Yeah that was my second thought. 
Off the topic, Is there any downside with the specified setup ( which hoists common used dev dependencies at the root Level) or Is this something not recommended due to any strong reason?

**Comment by ljharb** [comment]
The downside I can see is that you don't have a clear picture of which subprojects need which dev deps at which versions.

**Comment by ljharb** [comment]
Closing for now; these questions seem answered.
