### ISSUE TITLE
CI  Cannot find module 'typescript'

### ISSUE THREAD

**Issue by fyangstudio** [benmosher/eslint-plugin-import#1809]
Error:
`Cannot find module 'typescript'`
with eslint-plugin-import@.2.21.1 in CI:

https://travis-ci.com/github/raxjs/rax-vscode-extensions/builds/170236677
![image](https://user-images.githubusercontent.com/9896768/84009463-debf5300-a9a5-11ea-8d75-45774006d67b.png)

eslint-plugin-import@2.20.0 is ok.

**Comment by ljharb** [comment]
That doesn’t make any sense to me; 2.21.0 unconditionally required typescript (#1805), but 2.21.1 only does so when encountering typescript nodes.

Can you share the code it’s erroring on?

**Comment by fyangstudio** [comment]
It's happened in **travis CI** env.
It's works OK and no error occurred in my local development env as well.

I use the same Node and NPM version, with same command travis CI env failed,  local development env is OK.

Code: 
https://unpkg.alibaba-inc.com/browse/eslint-config-rax@0.0.3/rules/base.js

**Comment by ljharb** [comment]
[This line](https://github.com/raxjs/rax-scripts/blob/master/.travis.yml#L7) is unnecessary (the local one is used), but otherwise nothing looks out of place, and I can't reproduce it locally.

(I'm not sure why `npm run setup` is so abysmally slow, it seems to take longer than most lerna monorepos I've used)

Have you tried deleting all your travis-ci caches, and then rerunning the failed builds?

**Comment by fyangstudio** [comment]
It's seems good, when i remove travis-ci caches.
