### ISSUE TITLE
Webpack alias not working

### ISSUE THREAD

**Issue by wenfangdu** [benmosher/eslint-plugin-import#1851]
.eslintrc.js
```js
const path = require('path')

module.exports = {
  env: {
    node: true,
  },
  extends: ['plugin:vue/essential', 'eslint:recommended', '@vue/prettier'],
  parserOptions: {
    parser: 'babel-eslint',
  },
  plugins: ['import'],
  root: true,
  rules: {
    'import/exports-last': 'warn',
    'import/extensions': ['warn', 'ignorePackages'],
    'import/first': 'warn',
    'import/newline-after-import': 'warn',
    'import/no-duplicates': 'error',
    'import/no-relative-parent-imports': 'warn',
  },
  settings: {
    'import/resolver': {
      webpack: {
        config: {
          resolve: {
            alias: {
              '@': path.resolve('src'),
            },
          },
        },
      },
    },
  },
}
```
package.json
```
    "eslint-import-resolver-webpack": "^0.12.2",
    "eslint-plugin-import": "^2.22.0",
```
Result
![image](https://user-images.githubusercontent.com/28700378/87130182-141cd080-c2c5-11ea-9462-dc6fbf62da0d.png)

**Comment by ljharb** [comment]
Try adding `node: {}` after `webpack:` in the `import/resolver` settings?

**Comment by wenfangdu** [comment]
@ljharb Hi, I've added node setting and installed node plugin, but issue persists.
``` 
 settings: {
    'import/resolver': {
      node: { moduleDirectory: ['node_modules', 'src'] },
      webpack: {
        config: {
          resolve: {
            alias: {
              '@': path.resolve('src'),
            },
            modules: ['node_modules', 'src'],
            extensions: ['.js'],
          },
        },
      },
    },
  },
 "eslint-import-resolver-node": "^0.3.4",
```

**Comment by wenfangdu** [comment]
I think `eslint-plugin-import` clear knows my alias, but just doesn't function correctly 
![image](https://user-images.githubusercontent.com/28700378/87242274-bb347000-c45d-11ea-8667-dfa3e50052ed.png)
![image](https://user-images.githubusercontent.com/28700378/87242280-cedfd680-c45d-11ea-8b0d-c961d70a0f49.png)

**Comment by 3nuc** [comment]
In Case 2 above (warning for '@/components/test' and no warning for @/util) there's an issue with the implementation of checking for scoped modules in the `import/extensions` rule.


Using the `@` webpack alias (default in Vue projects) is the letter that also happens to be used by npm to mark scoped modules eg. `@vue/cli`. The problem is that `eslint-plugin-import` thinks `@/util` is a scoped module.

See https://github.com/benmosher/eslint-plugin-import/blob/master/src/rules/extensions.js#L132
```js
 function isExternalRootModule(file) {
      const slashCount = file.split('/').length - 1

      if (isScopedModule(file) && slashCount <= 1) return true // <----------- problem here
      if (isExternalModule(file, context, resolve(file, context)) && !slashCount) return true
      return false
    }

```

and the `isScopedModule` implementation (https://github.com/benmosher/eslint-plugin-import/blob/master/src/core/importType.js#L95):

```js
export function isScopedModule(name) {
  return name.indexOf('@') === 0
}
```

`if(isScopedModule('@/util') && slashCount <= 1)` is a false positive.

I think the implementation for isScopedModule should be `return name.indexOf('@') === 0 && !name.startsWith('@/')` and that'll do it

**Comment by gaoqiang19514** [comment]
>   extensions: ['.js', '.jsx', '.vue'],

```
    settings: {
        'import/resolver': {
            webpack: {
                config: {
                    resolve: {
                        alias: {
                            '@': path.resolve('src'),
                        },
                        extensions: ['.js', '.jsx'],
                    },
                },
            },
        },
    },
```
It's work for me!
