### ISSUE TITLE
'import/extensions': ['warn', 'always'] not working

### ISSUE THREAD

**Issue by wenfangdu** [benmosher/eslint-plugin-import#1914]
Rules
`'import/extensions': ['warn', 'always']`
No warning
![image](https://user-images.githubusercontent.com/28700378/94635955-6a1e7480-0306-11eb-85a9-cec44ccb353d.png)
According to the `import/extensions` doc, this should be warned
![image](https://user-images.githubusercontent.com/28700378/94636027-94703200-0306-11eb-9d3a-50bb0c1fdd4b.png)

**Comment by ljharb** [comment]
Why should that be warned? That’s a bare identifier, not a file path.

**Comment by wenfangdu** [comment]
@ljharb Sorry, but the doc says so.
![image](https://user-images.githubusercontent.com/28700378/94639913-ea95a300-030f-11eb-8476-b137bc07abe6.png)

**Comment by ljharb** [comment]
Hmm, that seems like it should be a bug.

**Comment by wenfangdu** [comment]
Please see these two lines, with `'import/extensions': ['warn', 'always']`, the first identifier is warned, the second is not.
![image](https://user-images.githubusercontent.com/28700378/96082640-2faffc80-0eee-11eb-8a7c-047a466d0e3e.png)

**Comment by ljharb** [comment]
Ah, thanks for being persistent. In that case, `vis-network` is the package, `vis-network/peer` is a file inside a package. The docs for "always" say that `express` is allowed (because `express.js` wouldn't work), but `express/index` is not allowed, and it must be `express/index.js`.

Similarly, `vis-network` is always allowed, but `vis-network/peer` is expected to be `vis-network/peer.js`.

With the new "exports" field (which we don't support yet), entry points to packages won't necessarily *have* an extension - and we'll have to adapt the rule to detect those cases - but in the meantime, this all seems correct to me.

**Comment by wenfangdu** [comment]
@ljharb Thank you for staying with me. 
> The docs for "always" say that express is allowed (_because express.js wouldn't work_)

If that's the reason `express` is allowed, I think `vis-network/peer` should be too, since it's not a file, it's actually a package too.
![image](https://user-images.githubusercontent.com/28700378/96084015-e8773b00-0ef0-11eb-9c5e-be52a86f4ca5.png)
Is `export * from "./esm";` the _not supported new "exports" field_ you mentioned? If so, it is correct.

**Comment by ljharb** [comment]
Indeed, in that case, `vis-network/peer/index.js` is what would satisfy the rule.

However, yes, in this case it's native node ESM, and that's not something we support yet.

**Comment by ljharb** [comment]
In particular, that package is broken - it doesn't declare `"type": "module"`, and thus, `.js` file are *always* CJS, not ESM, and use of `export` in it is invalid.

**Comment by wenfangdu** [comment]
@ljharb I see, thank you.
