### ISSUE TITLE
Front page makes the project look unsupported

### ISSUE THREAD

**Issue by shamilovtim** [benmosher/eslint-plugin-import#1989]
Just thought Id give you a heads up that this is going on:

<img width="1256" alt="Screen Shot 2021-02-09 at 7 09 46 PM" src="https://user-images.githubusercontent.com/3495974/107445465-7b745a80-6b0a-11eb-8add-738fbf9b3e33.png">

It looks like people put in a lot of effort here so it's shame that the front page doesn't reflect how updated the project actually is

**Comment by ljharb** [comment]
Thanks!

The date is because github shows the commit author date and not the push date; we can't do anything about that.

For the releases, i'd either have to start remembering to make a release for every new package update (ugh) or delete the existing ones.

I've made a release for the latest version, at least.
