### ISSUE TITLE
Allow to require from internal project file with `import/no-extraneous-dependencies`

### ISSUE THREAD

**Issue by piranna** [benmosher/eslint-plugin-import#2066]
When importing or requireing an internal file instead of the raw project export, `import/no-extraneous-dependencies` fails. This is a valid use case, so for example requires to `@apollo/client/link/error` should be successful if the `@apollo/client` package is included in `package.json` file, but right now it's failing since it checks for the full string.

**Comment by ljharb** [comment]
May be related to #2065 (cc @paztis)

**Comment by piranna** [comment]
Seems related, yes.

**Comment by paztis** [comment]
As I explain in the defect #2072, we're recursively searching for the 1st package.json in the  @apollo/client/link/error path.
Here we found it in @appolo/client folder
It means a dependency to @appolo/client need to be added.
What exactly is the error you have ? and what is the resolver you use ?

**Comment by piranna** [comment]
The error I have is that's asking to install a package that its name is the full `@apollo/client/link/error`, instead of just only `@apollo/client`. I'm using the default resolver used by Node.js v16.

**Comment by paztis** [comment]
Is there any package.json under the folder node_modules/@apollo/client/link/error ?

**Comment by piranna** [comment]
> Is there any package.json under the folder node_modules/@apollo/client/link/error ?

Surprissingly yes, I would bet it was not there before:

```json
{
  "name": "@apollo/client/link/error",
  "main": "error.cjs.js",
  "module": "index.js",
  "types": "index.d.ts",
  "sideEffects": false
}
```

It doesn't make any sense, I've reviewed other folders in the installed `@apollo/client` package and there's other `package.json` files, I don't understand what does they do there...

**Comment by piranna** [comment]
You have Apollo client code at https://github.com/apollographql/apollo-client, and link error at https://github.com/apollographql/apollo-client/tree/main/src/link/error.

**Comment by paztis** [comment]
Try a fresh install then verify the folder.

**Comment by paztis** [comment]
solution I propose in #2072 might resolve your problem. It's will be a little less strict on the imports but might be enough for these cases

**Comment by gabrielrtakeda** [comment]
I think that my problem is related to this...

I'm getting the linting error:

<img width="1059" alt="Screen Shot 2021-05-24 at 11 34 04" src="https://user-images.githubusercontent.com/5435389/119365179-104c2f80-bc86-11eb-8020-93a9f198bd93.png">

Where I'm importing like:

![image](https://user-images.githubusercontent.com/5435389/119365336-3540a280-bc86-11eb-98e5-036f793c0b85.png)

In my `node_modules` I have:

<img src="https://user-images.githubusercontent.com/5435389/119365546-66b96e00-bc86-11eb-9ffa-dc1fd5c4737a.png" alt="image" width="400">

And have `preact` in `package.json` dependencies:

<img width="488" alt="Screen Shot 2021-05-24 at 11 52 19" src="https://user-images.githubusercontent.com/5435389/119365703-97010c80-bc86-11eb-821f-50d28aa7305a.png">

Is this actually, the expected behavior?
I start to get this linting error after `v2.23.0`

**Comment by paztis** [comment]
Ok understood. Preact/hook is a real package with a package.json. 
But this package is. Only available under master preact one.

I think one fix can solve it and all other defects.
The module resolution returns us 'preact/hooks' 
We can validate it we've exactly this on or one of its ancestors in our dependencies.

If we found package a/b/c, no errors if in dependencies we've got 'a' or 'a/b' or 'a/b/c'

@ljharb what do you think about ?

**Comment by ljharb** [comment]
`preact/hooks` doesn't start with `@` or contain `node_modules`, so yes, that should come from the `preact` package.

**Comment by paztis** [comment]
I've created the PR #2097 for this. Can you look at it ?
