### ISSUE TITLE
Webpack resolver, no-unresolved and atom/sublime

### ISSUE THREAD

**Issue by tleunen** [benmosher/eslint-plugin-import#260]
I first entered an issue on atomlinter (see https://github.com/AtomLinter/linter-eslint/issues/554), but I'm not sure it's an issue with atomlinter since I've having the same issue in Sublime.

So the issue is that atom/sublime is reporting an error with no-resolved and the webpack resolver, but when I lint the file manually outside of the editor, it doesn't report the error.

Maybe the editor doesn't read the settings from the eslintrc file?

**Comment by tleunen** [comment]
So after investigation, it's because the root path wasn't correct.

I changed my webpack configuration for the root path, from `path.resolve('./src')` to `path.resolve(__dirname, './src')` and the issue was gone.

This is because in the editor, the root is the directory of the current file, not the project root.
I'm not sure if this is an issue of the webpack resolver, or because we should always resolve from the project root (in my case `__dirname` is correct since I have the webpack config file at the same "level" than my source directory).

I'm closing the issue since I have a fix for it. But @benmosher, feel free to reopen or add a fix inside the webpack resolver if it's possible, since in the webpack doc, it says `path.resolve('./src')` should be enough (https://webpack.github.io/docs/configuration.html#resolve-root)

**Comment by benmosher** [comment]
Ah, yes. There is a field for SublimeLinter called `chdir` that sets the working directory to whatever you want. You can set it to be the project root, see [this bit in the README](https://github.com/benmosher/eslint-plugin-import/blob/master/README.md#sublimelinter-eslint). 

If you were to configure `chdir` to match the directory where you normally run Webpack, the `__dirname` would probably be unnecessary. 

I am not familiar with Atom, so I'm not sure if there is an analogous setting. 

Also, Webpack would likely exhibit the same behavior if you were to use `webpack` from a different folder, but that is an absurd example since Webpack is usually executed from the project root, from a terminal or an npm script or something like that. 

I'm not sure what can be done here; I don't know how the plugin could intuit the directory in which you normally execute Webpack, so I think I like either what you've done (absolute config paths) or something like `chdir` that instructs the editor to run the lint process in an explicit working directory. 

If something else is possible, I'm open to discussing, but I'm not sure what else could be done. 

Thanks for the great detail and noting your workaround! 😄

**Comment by tleunen** [comment]
Yep indeed, I don't think we can do much inside the resolver...

Just a quick note though, `path.resolve` already returns an absolute path. With 2 arguments, the first is from which directory the "source" has to be resolved from (See https://nodejs.org/docs/latest/api/path.html#path_path_resolve_from_to). So it's not a big change to specify the root project :) And it has the advantage to work without any changes for all editors.
