### ISSUE TITLE
`extensions`: how to specify a default while specifying granular extensions?

### ISSUE THREAD

**Issue by ljharb** [benmosher/eslint-plugin-import#390]
I'd like the default to be "always" but i'd like `js` and `jsx` to be "never". How do I specify this? The schema only allows a string, or an object, but not both.

**Comment by ljharb** [comment]
(Similarly, I should be able to specify "never" and have a specific extension be "always")

It's not clear to me how to ensure that.

**Comment by benmosher** [comment]
Ah, interesting. I'm not sure how you'd do that, either. Sounds like a reasonable goal though.

**Comment by ljharb** [comment]
My thinking was that the schema would allow a string *and* an object - the string constitutes the default, and the object has granular overrides.

**Comment by ljharb** [comment]
Any update on this?

**Comment by benmosher** [comment]
I like your proposal:

> ... the schema would allow a string and an object - the string constitutes the default, and the object has granular overrides.

Don't think it constitutes a breaking change, since the first arg can still be a string or object, but the second one _must_ be an object if the first is a string, and the second must not be provided if the first is an object.

I'm not planning on working on this anytime soon. I'd be happy to accept and ship a PR, though.

**Comment by ljharb** [comment]
Finally filed https://github.com/benmosher/eslint-plugin-import/pull/555 to fix this :-)

**Comment by ljharb** [comment]
Yay, thanks! Waiting patiently now for the release :-)
