### ISSUE TITLE
delete `export` rule?

### ISSUE THREAD

**Issue by benmosher** [benmosher/eslint-plugin-import#582]
Both Babylon and Espree have made changes to make exporting duplicate named or default exports syntax errors.

This makes it hard to test this rule since it fails on syntax errors.

Seems like the simplest thing is to pull it out of v2.

**Comment by jfmengels** [comment]
To me, this error is worth having if it can help report errors that would otherwise be met at runtime. At the moment, I don't think that Babel reports errors when compiling import/export syntax. But if I'm not mistaken, that should happen soon-ish, as they are using Babylon under the hood.

Since there is now a parsing error when export is incorrectly used, all other rules will trigger, so I don't think this will provide much value. Especially as the error messages seem to be quite descriptive too (:tada:).

So, IMO, this is worth keeping, if and only if there are other (relatively popular) parsers that still support incorrect export syntax. As far as I know and use, there is only the default parser (Espree) and babel-eslint (Babylon). So if you can't think of another, I'm :+1: with removing the rule.

**Comment by benmosher** [comment]
Yeah, turns out there are a handful of `export * from '...'` cases that this rule does catch. 

I'm just commenting all the failing cases and keeping the code as is.
