### ISSUE TITLE
no-extraneous-deps globs don't also check against `process.cwd() + glob`

### ISSUE THREAD

**Issue by ljharb** [benmosher/eslint-plugin-import#602]
I want to set my glob to `tests/**`, so that only the top-level "tests" dir can contain things that require dev deps.

However, this rule compares against the full absolute path of the file, which includes the path to the project root - which isn't really useful, and forces people to start 100% of their globs with "**/".

I'd like the rule to check both against the full filename, and also against `path.join(process.cwd(), glob)`, to remove the need for this boilerplate in airbnb's shared config.

**Comment by jfmengels** [comment]
Sounds like a good idea.

The one point I'm not familiar with is whether using `process.cwd()` is the right way to do this. Because that would mean you would get different results based on the directory we run ESLint in, right?

I think it would be more correct to replace `process.cwd()` by the root of of the project (probably where `package.json` is located). But as we saw recently, especially with this rule, that's more complicated than expected with monorepos. So I'd probably fall back to the use of `process.cwd()`.

Do you think that running ESLint not from the root folder is a sufficiently rare case to use `process.cwd()`? I always run from the root, but others may do it differently.

cc @benmosher if you have time to give your opinion on this

**Comment by ljharb** [comment]
Yes, I don't think any command should ever be run anywhere except from the project root.

There's a thread on eslint about locating the project root, and they concluded that process.cwd was best.

**Comment by jfmengels** [comment]
Ok, that sounds good to me then. Help welcome!

(cc @knpwrs, if you feel like helping out again :smile:)

**Comment by knpwrs** [comment]
@ljharb Can you link to that thread for reference?

**Comment by ljharb** [comment]
@knpwrs https://github.com/eslint/eslint/issues/3974#issuecomment-144197496

**Comment by knpwrs** [comment]
So... speaking of multiple `.eslintrc` files how should this behave in that context? An `.eslintrc` file in the `test` directory would still execute `process.cwd()` in the root directory if I understand that discussion correctly.

I realize your situation is a single `.eslintrc` file but I'd want to support all usages.

**Comment by ljharb** [comment]
@knpwrs yes, that's the intention

**Comment by benmosher** [comment]
Using process.cwd makes sense to me. A number of things already do this. 

It can cause problems with editor integration, but I think the workarounds in those cases are well understood.
