### ISSUE TITLE
Question: How does this package read the package.json?

### ISSUE THREAD

**Issue by amilajack** [benmosher/eslint-plugin-import#713]
Is there a specific line someone can point to where this plugin reads the package.json file to validate dependencies? Thanks. I need this kind of functionality of a plugin i'm working on.

**Comment by jfmengels** [comment]
We use [`read-pkg-up`](https://www.npmjs.com/package/read-pkg-up) ([here](https://github.com/benmosher/eslint-plugin-import/blob/master/src/rules/no-extraneous-dependencies.js#L9-L13). You also have [`pkg-up`](https://www.npmjs.com/package/pkg-up) if you need to know the location of it rather than straight out read it.

Be warned that this may not work well in "monorepo" projects that have multiple package.json files.

**Comment by amilajack** [comment]
Thanks
