### ISSUE TITLE
no-mutable-exports fails when exporting types (flow)

### ISSUE THREAD

**Issue by Erid** [benmosher/eslint-plugin-import#758]
I was trying to do an export like the following:
```
export type { Options }
```

Having that on the file would throw the following exception:
![image](https://cloud.githubusercontent.com/assets/703220/23471807/31433180-fe70-11e6-8512-a6ab4e9d8026.png)

By just removing that rule I was able to make it keep working, I think it would be nice for this plugin to also support flow (or not crash because of it).

**Comment by demands** [comment]
@ljharb, @benmosher -- I was running into this issue, and wrote a test case, and then was very confused when I couldn't get it to fail.... until I looked closer and realized that the bug had already been fixed in master! (See #660.)

Any chance you could push out a new bugfix version for this? Thanks!!

**Comment by ljharb** [comment]
If the fix was done in November, why was this issue posted in March?

**Comment by Erid** [comment]
I believe the latest version published on NPM is from November 7 (2.2.0 at baa6b8a) and the commit that fixes this was made on November 14. My finding was based only on the published version.

**Comment by ljharb** [comment]
ah, gotcha. looks like we're overdue for a release :-)
