### ISSUE TITLE
How to ignore partially with devDependency: false

### ISSUE THREAD

**Issue by kopax** [benmosher/eslint-plugin-import#763]
I need to send an eslint if dev dependency are imported within the application but not within the unit test file that end with `*.test.js`.

These can benefit of the dev dependency. How can I take care of that ?

**Comment by ljharb** [comment]
Since eslint does not have glob-based configuration, individual rules would have to support it to get their benefit in colocated tests, without a plethora of eslintrc files.

Luckily for you, this particular rule does - see the [docs](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md).

Another alternative is keeping tests wholly separate from implementations (the most common approach) which means you'd have only two eslintrc files; the root, and the tests override.

**Comment by kopax** [comment]
I have read and ignored this plugin. But I haven't tried it.
That's why I ask the question this way.

I am afraid that doing: 

    "import/no-extraneous-dependencies": ["error", {"devDependencies": false}]

Will also complain of my test files that use devDependency.

**Comment by ljharb** [comment]
Instead of `false`, pass an array of globs. If you read the rule documentation I linked to, you'll see that.
