### ISSUE TITLE
How to debug a custom resolver? All logs and errors are swallowed

### ISSUE THREAD

**Issue by callumlocke** [benmosher/eslint-plugin-import#819]
I'm trying to write a custom resolver, and when I run `eslint .`, it seems to hide any `console.log` coming from my resolver, and it quietly swallows any errors thrown by it. So all I can see is "Unable to resolve path to module..." errors.

How am I supposed to debug my resolver?

**Comment by RobinClowers** [comment]
@callumlocke Check out this PR: https://github.com/benmosher/eslint-plugin-import/pull/599 it will print stack traces for actual errors so you can track them down.

**Comment by Izhaki** [comment]
The plugin itself uses `debug`:

```js
const log = require('debug')('eslint-plugin-import:resolver:node');

exports.interfaceVersion = 2;
exports.resolve = function (source, file, config) { 
  log('Resolving:', source, 'from:', file);
  //...
}
```

https://github.com/benmosher/eslint-plugin-import/blob/master/resolvers/node/index.js

But for me `console.log` works just fine.

I've landed on this issue because I couldn't see `console.log`, but then I realised this was because my eslint config was incorrect (I've copied/pasted the `settings` block into the existing `settings` block).

I think this issue can be closed.
