### ISSUE TITLE
Parse error with image import when using webpack

### ISSUE THREAD

**Issue by OndeVai** [benmosher/eslint-plugin-import#942]
I have the following script set up in my package.json:

`"lint": "node_modules/.bin/esw webpack.config.* src tools",`

In addition in my webpack dependency chain I have an import of an image:

`import loadingImg from './Loader.gif';`

Also, I have a valid loader to handle that image (and webpack still works):

```
{
    test: /\.(jpe?g|png|gif|svg)$/i,
    loader: 'url-loader?limit=30000&name=images/[name].[ext]'
}
```

When I run the script task using `npm run lint`, I get the following errors:

```
Parse errors in imported module './Loader.gif': Unexpected token ' ' (1:7)  import/namespace
Parse errors in imported module './Loader.gif': Unexpected token ' ' (1:7)  import/default
```

**Comment by benmosher** [comment]
Easy fix, just need to configure `import/ignore` to avoid parsing your image assets: https://github.com/benmosher/eslint-plugin-import#importignore

**Comment by javierguzman** [comment]
Sorry to bring this up @benmosher , but I updated my repository and started getting the "import/no-extraneous-dependencies" error for imported images when using an alias e.g. @Images/my_image.png

Is ignoring images the way to go? Before it was working ok and I was using eslint to tell me indirectly it there was something wrong with the path image.

Any hint would be appreciated. Otherwise I will just leave with the import/ignore .

Thank you in advance and regards

**Comment by ljharb** [comment]
@javierguzman Yes, you should tell this plugin to ignore non-standard imports, like images and stylesheets and fonts, none of which can actually be imported by any javascript engine that exists.

**Comment by javierguzman** [comment]
Sorry @ljharb but I have been all day trying to make "import/ignore" work properly.

If I have:
`"import/ignore": ["/*.png/", "/*.jpg/"]`
Then my webpack build is ok as expected. However, VSCode highlights my "import myimage from @Images/my_image.png" as red due to "import/no-extraneous-dependencies".

On the other hand if I have:
`"import/ignore":["*.png", "*.jpg"]`
Then the highlight red error from VSCode goes away but my webpack build throws:
```
ERROR in Invalid regular expression: *.png: Nothing to repeat
Occurred while linting blablabla\Application\client\src\index.js:2
```

This seems very odd as everything was working before I updated stuff. Is this a known bug? It is like the eslint webpack plugin and the vscode eslint plugin reads the import/ignore field differently.

I use the same eslint configuration everywhere including the vscode eslint plugin. I can create a new issue if you think is not really related to this one.

Thank you in advance and regards

**Comment by ljharb** [comment]
Why is there a trailing slash in your config?

**Comment by ljharb** [comment]
Hmm - can you please file a new issue for this? There might be a bug.

**Comment by javierguzman** [comment]
Hello @ljharb  I have created the following issue #2230 with a repo included.

Regarding the trailing slash is because I have been trying to get rid of the error but it looks like a ping-pong one, if you know what I mean. Anyway, we can continue the conversation over there if you wish.
